[package]
name = "tether-project"
version = "0.1.0"
authors = ["Majedul Hoque <rumanbsl@gmail.com>"]
edition = "2018"

[dependencies]
tether="0.2.1"
web-view = "0.4.0"
serde_derive="1.0.80"
serde_json="1.0.33"
serde = "1.0.80"